// src/app/layout.tsx
'use client';

import '../globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { logout, getToken, getUserRole } from './lib/auth';
import { useState, useEffect } from 'react'; // <--- IMPORT useState dan useEffect

const inter = Inter({ subsets: ['latin'] });

// Pastikan file src/app/layout.ts ada dan mengekspor metadata
// export const metadata: Metadata = {
//   title: 'My Inventory App Frontend',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  const [mounted, setMounted] = useState(false); // <--- State baru untuk melacak apakah komponen sudah dimount

  useEffect(() => {
    setMounted(true); // <--- Setel menjadi true setelah komponen dimount di klien
  }, []);

  const token = getToken();
  const userRole = getUserRole();

  const handleLogout = async () => {
    await logout(router);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{ padding: '15px', background: '#f0f0f0', borderBottom: '1px solid #ddd', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '20px' }}>
          <Link href="/" style={{ textDecoration: 'none', color: '#007bff', fontWeight: 'bold' }}>
            Home
          </Link>
          <Link href="/products" style={{ textDecoration: 'none', color: '#007bff', fontWeight: 'bold' }}>
            Produk
          </Link>
          <Link href="/categories" style={{ textDecoration: 'none', color: '#007bff', fontWeight: 'bold' }}>
            Kategori
          </Link>
          <Link href="/orders" style={{ textDecoration: 'none', color: '#007bff', fontWeight: 'bold' }}>
            Pesanan
          </Link>

          {/* --- HANYA RENDER BAGIAN INI SETELAH KOMPONEN DIMOUT DI KLIEN --- */}
          {mounted && (
            !token ? (
              <>
                <Link href="/login" style={{ textDecoration: 'none', color: '#007bff', fontWeight: 'bold' }}>
                  Login
                </Link>
                <Link href="/register" style={{ textDecoration: 'none', color: '#007bff', fontWeight: 'bold' }}>
                  Daftar
                </Link>
              </>
            ) : (
              <>
                {userRole === 'ADMIN' && (
                  <Link href="/admin/users" style={{ textDecoration: 'none', color: '#28a745', fontWeight: 'bold' }}>
                    Manajemen Pengguna (Admin)
                  </Link>
                )}
                <button onClick={handleLogout} style={{ padding: '8px 15px', background: '#dc3545', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', marginLeft: 'auto' }}>
                  Logout
                </button>
              </>
            )
          )}
          {/* --- AKHIR BAGIAN YANG DIRENDER SETELAH DIMOUT --- */}
        </nav>
        {children}
      </body>
    </html>
  );
}